experiment: "first-experiment"
#testsnd: "" # 8bit, fusion, lofi, duduk, zelda

# for docker:
data_dir: "/data/dac-train"
validator_data_dir: "/data/dac-val"

data_frames: "data/dac-train.xlsx"
validator_data_frames: "data/dac-val.xlsx"

TransformerClass: "RopeCondDACTransformer" # "PostNormCondDACTransformerDecoder" # "ClassConditionedKeyTransformer" # 

vocab_size: 1024
num_tokens: 4

cond_params: 1 #1 (not counting the classes)
model_size: 512  #embedding+conditioning vect

Ti: 172 # 172 #86
Tt: 430 # must match the length of the sequences in the batch
batch_size: 8  #**


num_layers: 2 #**
num_heads: 8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 4 # 4 #4
dropout_rate: 0.2
learning_rate: 0.0005

num_epochs: 250 ### 800 

ErrorLogRate: 10 ### 10
checkpoint_interval: 50 ###50 # 25

