experiment: "smalltest100"

# data_dir: "private/testdata/train_sm_xxx"
# data_frames: "private/testdata/train_sm_xxx.xlsx"
# validator_data_dir: "private/testdata/val_xxx"
# validator_data_frames: "private/testdata/val_xxx.xlsx"

data_dir: "/home/lonce/scratchdata/syntexnew/dacdata7/all7"
data_frames: "/home/lonce/scratchdata/syntexnew/dacdata7/train_sm.xlsx"
validator_data_dir: "/home/lonce/scratchdata/syntexnew/dacdata7/all7"
validator_data_frames: "/home/lonce/scratchdata/syntexnew/dacdata7/train.xlsx"


TransformerClass: "RopeCondDACTransformer" # "PostNormCondDACTransformerDecoder" #  "ClassConditionedKeyTransformer" # 

vocab_size: 1024
num_tokens: 4

cond_params: 1 #1 (not counting the classes)
model_size: 64 # must be divisible by num_heads
#tblock_input_size: 32 #512  #embedding+conditioning vect

Ti: 86 # 172 #86
Tt: 430 # must match the length of the sequences in the batch
batch_size: 4  #**


num_layers: 2 #**
num_heads: 8 #8 # 8 # embed_size must be divisible by num_heads
forward_expansion: 3 #4 #4
dropout_rate: 0.2
learning_rate: 0.0005

num_epochs: 5 ### 800 

ErrorLogRate: 1 ### 10
checkpoint_interval: 5 ###50 # 25

